# Generated by Django 2.2.16 on 2022-01-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220114_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='hex_code',
            new_name='color',
        ),
    ]
