# Generated by Django 2.2.16 on 2022-01-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220114_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
