# Generated by Django 2.2.16 on 2022-01-24 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0011_auto_20220124_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(through='RecipeTags', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='recipes.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together={('user', 'recipe')},
        ),
        migrations.DeleteModel(
            name='RecipeTags',
        ),
    ]
